version: 2.1
orbs: 
  aws-auth: cardig/aws-auth@1.3.0
executors:
  python_executor:
    docker:
      - image: cimg/python:3.9.13
jobs:
  jira_code_review: 
    executor: python_executor
    steps:
      - checkout
      - run: echo "JIRA COde Review"
      - run:
          name: Jira_Python_Script
          command: |
#           python -m pip install --upgrade pip
            pip install requests
            python My_Jira_Oauth_Script.py
            python Jira_Oauth_Project_Details_Script.py
workflows:
  bt_workflow:
    jobs:
      - jira_code_review
